version: "3.8"

services:

    portainer:
        restart: unless-stopped
        image: portainer/portainer-ce
        container_name: sbr_portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 9000:9000

    sbr_rabbitmq:
        restart: unless-stopped
        image: rabbitmq:management-alpine
        container_name: sbr_rabbitmq
        hostname: sbr_rabbitmq
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - sbr_net_internal
            - sbr_net_external

            
    networks:
        sbr_net_internal: 
            driver: bridge
            internal: true
        
        sbr_net_external:
            driver: bridge
            