[package]
name = "robot_control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amiquip = "0.4 "
serde_json = "1.0"
serde = "1.0"
redis = "0.23.0"