[package]
name = "robot_control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphql_client = { version = "0.13.0", features = ["reqwest-blocking"] }
reqwest = "0.11.18"
serde = "1.0"
