FROM dustynv/jetson-inference:r35.3.1 as dev

# Install face_recognition
RUN pip3 install face_recognition

# Create a directory for the app
WORKDIR /sbr

# Copy source code
RUN rm -rf src
COPY ./src ./src

# Run main.py
CMD ["python3", "-u", "./src/main.py"]