version: "3.8"

services:
    sbr_portainer:
        restart: always
        image: portainer/portainer-ce
        container_name: sbr_portainer
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ~SBR/data/portainer/portainer-data:/data
        ports:
            - 9000:9000
        networks:
            - sbr_net_external


    sbr_serv_host_connector:
        restart: always
        image: sbr/sbr_serv_host_connector:1.0
        container_name: sbr_serv_host_connector
        volumes:
            - ~SBR/data/host_connector/requests:/app
        environment:
            RABBITMQ_HOST: "sbr_rabbitmq"
            HOST: "NX"
        build:
            context: ../../SBR_SERV/host_connector/
            target: dev
        networks:
            - sbr_net_swarm


networks:
    sbr_net_internal:
        driver: bridge
        internal: true

    sbr_net_external:
        driver: bridge

    sbr_net_swarm:
        driver: overlay
        attachable: true

