version: "3.8"

services:
    sbr_portainer_nx:
        restart: unless-stopped
        image: portainer/portainer-ce:latest
        container_name: sbr_portainer_nx
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /home/sbrnx/SBR/data/portainer/portainer-data:/data
        ports:
            - 9000:9000
        networks:
            - sbr_net_external
            - sbr_net_swarm


    sbr_serv_host_connector:
        restart: unless-stopped
        image: sbr/sbr_serv_host_connector:1.0
        container_name: sbr_serv_host_connector
        volumes:
            - /home/sbrnx/SBR/data/host_connector/requests:/app
        environment:
            RABBITMQ_HOST: "sbr_rabbitmq"
            RABBITMQ_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_PASS: ${RABBITMQ_DEFAULT_PASS}
            HOST: "NX"
        build:
            context: ../../SBR_SERV/host_connector/
            target: dev
        networks:
            - sbr_net_swarm
            
    
    sbr_serv_camera_streamer:
        restart: unless-stopped
        image: sbr/sbr_serv_camera_streamer:1.0
        container_name: sbr_serv_camera_streamer
        privileged: true
        devices:
            - /dev/video2:/dev/video0   # Infrared camera
            - /dev/video4:/dev/video1   # RGB camera
        build:
            context: ../../SBR_SERV/camera_streamer/
            target: dev
        ports:
            - 6000:6000/udp
        networks:
            - sbr_net_swarm
            - sbr_net_internal
            - sbr_net_external


networks:
    sbr_net_internal:
        driver: bridge
        internal: true

    sbr_net_external:
        driver: bridge

    sbr_net_swarm:
        driver: overlay
        attachable: true

