FROM dustynv/jetson-inference:r35.3.1 as dev

# Install face_recognition
RUN pip3 install face_recognition

# Install pyrealsense2
RUN pip3 install pyrealsense2

# Install pika
RUN pip3 install pika

# RUN mkdir pyrealsense2_build && \
#     cd pyrealsense2_build && \
#     git clone --branch development --depth=1 https://github.com/IntelRealSense/librealsense && \ 
#     cd librealsense && \
#     mkdir build && \ 
#     cd build && \ 
#     cmake \
#         -DBUILD_EXAMPLES=true \
# 	    -DFORCE_RSUSB_BACKEND=true \
# 	    -DBUILD_WITH_CUDA=true \
# 	    -DCMAKE_BUILD_TYPE=release \
# 	    -DBUILD_PYTHON_BINDINGS=bool:true \
# 	    -DPYTHON_EXECUTABLE=/usr/bin/python3 \
# 	    -DPYTHON_INSTALL_DIR=$(python3 -c 'import sys; print(f"/usr/lib/python{sys.version_info.major}.{sys.version_info.minor}/dist-packages")') \
# 	    ../ && \
#     make -j$(nproc) && \
#     make install

# RUN export PYTHONPATH=$PYTHONPATH:/usr/local/lib


# Create a directory for the app
WORKDIR /sbr

# Copy source code
RUN rm -rf src
COPY ./src ./src

# Run main.py
CMD ["python3", "-u", "./src/main.py"]