version: "3.8"

services:

    serial_connector:
        restart: "no"
        tty: true
        image: rust/serial_connector:1.0
        container_name: serial_connector
        devices: 
          - /dev/ttyUSB1:/dev/ttyUSB1
        build: 
            context: .
            target: prod   
