FROM rust:1.70 as build
RUN apt-get update
RUN apt-get install -y libudev-dev
RUN apt-get install -y libssl-dev 
RUN USER=root cargo new --bin serial_connector
WORKDIR /serial_connector

COPY ./Cargo.toml ./Cargo.toml

RUN cargo build --release
RUN rm src/*.rs

COPY ./src ./src
RUN rm ./target/release/deps/serial_connector*
RUN cargo build --release


FROM rust:1.70 as prod
COPY --from=build /serial_connector/target/release/serial_connector .
CMD ["./serial_connector"]
