version: "3.8"

services:

    sbr_portainer:
        restart: unless-stopped
        image: portainer/portainer-ce
        container_name: sbr_portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 9000:9000

    sbr_rabbitmq:
        restart: unless-stopped
        image: rabbitmq:management-alpine
        container_name: sbr_rabbitmq
        hostname: sbr_rabbitmq
        environment:
          RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
          RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
          RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - 5672:5672
            - 15672:15672
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 30s
            timeout: 10s
            retries: 5

    sbr_serv_serial_connector:
        restart: unless-stopped
        tty: true
        image: sbr/sbr_serv_serial_connector:1.0
        container_name: sbr_serv_serial_connector
        devices: 
            - /dev/ttyUSB0:/dev/ttyS0
        build: 
            context: ../../SBR_SERV/serial_connector/
            target: prod
        depends_on:
            sbr_rabbitmq:
                condition: service_healthy
        links: 
            - sbr_rabbitmq

    sbr_redis:
        restart: unless-stopped
        image: redis:alpine
        container_name: sbr_redis
        ports:
            - 6379:6379
            
