FROM rust as build
RUN apt-get update
RUN apt-get install -y libssl-dev 
RUN USER=root cargo new --bin graphql
WORKDIR /graphql

COPY ./Cargo.toml ./Cargo.toml

RUN cargo build --release
RUN rm src/*.rs

COPY ./src ./src
RUN rm ./target/release/deps/graphql*
RUN cargo build --release

FROM rust as prod
COPY --from=build /graphql/target/release/graphql .
CMD ["./graphql"]
