FROM nvcr.io/nvidia/l4t-ml:r35.2.1-py3 as dev

RUN apt-get update -y

# Install dependencies: https://github.com/dusty-nv/jetson-inference/blob/master/CMakePreBuild.sh
RUN apt-get install -y \
        git \
		dialog \
		libglew-dev \
		glew-utils \
		gstreamer1.0-libav \
		gstreamer1.0-nice \
		libgstreamer1.0-dev \
		libgstrtspserver-1.0-dev \
		libglib2.0-dev \
		libsoup2.4-dev \
		libjson-glib-dev \
		python3-pip \
		python3-packaging \
		qtbase5-dev \
        libpython3-dev \ 
        python3-numpy

# Install Gstreamer: https://github.com/dusty-nv/jetson-containers/blob/master/packages/gstreamer/Dockerfile
RUN apt-get purge -y '*opencv*' || echo "existing OpenCV installation not found" && \
    apt-get install -y \
        cmake \
        nano \
        mesa-utils \
        lsb-release \
        gstreamer1.0-tools \
        gstreamer1.0-libav \
        gstreamer1.0-rtsp \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-bad \
        gstreamer1.0-plugins-ugly \
        libgstreamer-plugins-base1.0-dev \
        libgstreamer-plugins-good1.0-dev \
        libgstreamer-plugins-bad1.0-dev \
        gstreamer1.0-plugins-rtp \
        python3-gi \
		python3-gst-1.0 \
        libgstrtspserver-1.0-0

RUN apt update -y && apt upgrade -y

# Copy Gstreamer in a temporary directory
RUN cp -r /usr/include/gstreamer-1.0 /tmp

# Install Opencv: https://github.com/dusty-nv/jetson-containers/blob/master/packages/opencv/opencv_builder/Dockerfile
# https://github.com/dusty-nv/jetson-containers/blob/master/packages/opencv/config.py
RUN ./tmp/opencv_install.sh 'https://nvidia.box.com/shared/static/2hssa5g3v28ozvo3tc3qwxmn78yerca9.gz' 'OpenCV-4.5.0-aarch64.tar.gz'

# Copy Gstreamer from the temporary directory
RUN cp -r /tmp/gstreamer-1.0 /usr/include && \
    rm -rf /tmp/gstreamer-1.0 && \
    ln -s /usr/lib/$(uname -m)-linux-gnu/libgstwebrtc-1.0.so.0 /usr/lib/$(uname -m)-linux-gnu/libgstwebrtc-1.0.so

# Clone and build jetson-utils
RUN mkdir jetson-utils_build && \ 
    cd jetson-utils_build && \
    git clone --depth=1 https://github.com/dusty-nv/jetson-utils && \ 
    cd jetson-utils && \ 
    mkdir build && \ 
    cd build && \ 
    cmake ../ && \ 
    make -j$(nproc) && \ 
    make install && \ 
    ldconfig && \
    cd / \
    rm -rf jetson-utils_build

# Create a directory for the app
WORKDIR /sbr

# Copy source code
RUN rm -rf src
COPY ./src ./src

# Run main.py
CMD ["python3", "-u", "./src/main.py"]