FROM nvcr.io/nvidia/l4t-ml:r36.2.0-py3 as dev

# Install Gstreamer: https://github.com/dusty-nv/jetson-containers/blob/master/packages/gstreamer/Dockerfile
RUN apt-get update && \
    apt-get purge -y '*opencv*' || echo "existing OpenCV installation not found" && \
    apt-get install -y --no-install-recommends \
        dialog libglew-dev \
        glew-utils \
        libgstrtspserver-1.0-dev \
        libglib2.0-dev \
        libsoup2.4-dev \
        libjson-glib-dev \
        qtbase5-dev \
        lsb-release \
        libgstreamer1.0-dev \
        gstreamer1.0-tools \
        gstreamer1.0-libav \
        gstreamer1.0-rtsp \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-bad \
        gstreamer1.0-plugins-ugly \
        libgstreamer-plugins-base1.0-dev \
        libgstreamer-plugins-good1.0-dev \
        libgstreamer-plugins-bad1.0-dev \
        libgstrtspserver-1.0-0 \
        python3-gi \
        python3-gst-1.0 && \
    if [ `lsb_release --codename --short` != 'bionic' ]; then \
    apt-get install -y --no-install-recommends \
		  gstreamer1.0-plugins-rtp; \
    else echo "skipping packages unavailable for Ubuntu 18.04"; fi \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

# Copy Gstreamer in a temporary directory
# RUN cp -r /usr/include/gstreamer-1.0 /tmp

RUN mkdir -p /usr/local/include/gstreamer-1.0/gst && \
    cp -r /usr/include/gstreamer-1.0/gst/webrtc /usr/local/include/gstreamer-1.0/gst && \
    ls -ll /usr/local/include/ && \
    ls -ll /usr/local/include/gstreamer-1.0/gst/webrtc

# Install Opencv: https://github.com/dusty-nv/jetson-containers/blob/master/packages/opencv/opencv_builder/Dockerfile
# RUN ./opt/opencv_install.sh

# Copy Gstreamer from the temporary directory
# RUN cp -r /tmp/gstreamer-1.0 /usr/include && \
#     rm -rf /tmp/gstreamer-1.0 && \
#     ln -s /usr/lib/$(uname -m)-linux-gnu/libgstwebrtc-1.0.so.0 /usr/lib/$(uname -m)-linux-gnu/libgstwebrtc-1.0.so

RUN cp -r /usr/local/include/gstreamer-1.0/gst/webrtc /usr/include/gstreamer-1.0/gst && \
    ln -s -f /usr/lib/$(uname -m)-linux-gnu/libgstwebrtc-1.0.so.0 /usr/lib/$(uname -m)-linux-gnu/libgstwebrtc-1.0.so 

# Clone and build jetson-utils
RUN mkdir jetson-utils_build && \ 
    git clone https://github.com/dusty-nv/jetson-utils && \ 
    cd jetson-utils && \ 
    mkdir build && \ 
    cd build && \ 
    cmake ../ && \ 
    make -j$(nproc) && \ 
    make install && \ 
    ldconfig && \
    cd / && \
    rm -rf jetson-utils_build

# RUN apt-get install libgstrtspserver-1.0 libgstreamer1.0-dev

# Create a directory for the app
WORKDIR /sbr

# Copy source code
RUN rm -rf src
COPY ./src ./src

# Run main.py
CMD ["python3", "-u", "./src/main.py"]