name: Deploy Robot - NX

on:
  workflow_dispatch:
  
jobs: 
  deploy:
    runs-on: [self-hosted, sbr-nx]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Compose
        working-directory: ./SBR_NX/DevOps
        run: docker compose up --build -d
      - name: Delete old images
        run: docker image prune -f